const ACTION_TYPES = {
    FETCH_APPCONFIG: 'FETCH_APPCONFIG',
    FETCH_TASK: 'FETCH_TASK',
    FETCH_USERDETAILS: 'FETCH_USERDETAILS',
    POST_CREATETASK: 'POST_CREATETASK'
}

export default ACTION_TYPES;